### ISSUE TITLE
I can't see the examples working from site

### ISSUE THREAD

**Issue by delmohf** [sketchpunklabs/ossos#1]
Hi:

I tried to see the examples so I clone the repo and follow the installation steps: _npm install_, _npm run dev_, I found nothing on localhost:3000, then I tried _npm run build:site_ and _npm run preview-site_ but I found nothing on localhost:5000 then I navigated to http://localhost:5000/examples/threejs/000_gltf2_mesh.html but I got an error on Starter.js at line 51 from console:

_Uncaught TypeError: Cannot read properties of undefined (reading 'substring')  at Starter.cd2d3b33.js:51_

Am I missing some obvious step? How can I see the examples in the browser?

Thanks!

**Comment by delmohf** [comment]
Thanks! Ok, I cloned the res repository and put its content in examples\_res then run: 

_npm run dev_ 

but only these examples worked:

http://localhost:3000/examples/threejs/000_gltf2_mesh.html (just the load of nabba.gltf)
http://localhost:3000/examples/threejs/007_ik_solvers.html

with all other examples I got a JavaScript error in devtools console, e.g.:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0') at Object.multiply8 (quat2.js:596)

Are they errors to be fixed or should I do something else to see the examples in the browser????

PS: I am using Chrome and Windows Subsystem for Linux (WSL) so vite webserver is running on Ubuntu.

**Comment by sketchpunk** [comment]
Only 001_skin_dq.html & 001_skin_dqt.html are using quat2.js which is from the gl-matrix math library.  The other examples shouldn't have that error since the rest of the examples are using Matrix Skinning, not dual quaternions.

At this point I'm not sure what the problem might be, maybe vite or the whole dev setup doesn't work well under ubuntu.

**Comment by sketchpunk** [comment]
I just noticed that examples on my end don't work either. There was a bug that went by unnoticed from my last commit. Its all fixed up in the latest commit. Hopefully this will fix the issues you where experiencing.

It was related to me changing bone.pidx into a non-nullable type, some places where still testing for nulls which resulted in certain conditions running when they shouldn't which lead to weird errors coming from gl-matrix.

**Comment by delmohf** [comment]
Thanks!!!, now all examples work fine. ;)

**Comment by arpu** [comment]
this is still a problem on latest master?

i get 

```
index.ts:512          GET http://localhost:3000/examples/_res/models/nabba/nabba.gltf net::ERR_ABORTED 404 (Not Found)
fetch @ index.ts:512
(anonymous) @ 000_gltf2_mesh.html?html-proxy&index=0.js:14
load (async)
(anonymous) @ 000_gltf2_mesh.html?html-proxy&index=0.js:10
UtilGltf2.js:25 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getMesh')
    at Function.loadMesh (UtilGltf2.js:25:24)
    at 000_gltf2_mesh.html?html-proxy&index=0.js:15:29

```

**Comment by arpu** [comment]
wups found the _setup.txt file in _res

**Comment by sketchpunk** [comment]
Yea, the res folder is kinda big with lots of binary which makes me not want to include it into the repo. Think i'm going to make an Index page for examples that links to everything, plus leave a note that people will need to download the res repo separately for meshes, animations & textures.
