### ISSUE TITLE
Error following setup instructions during `npm run dev`

### ISSUE THREAD

**Issue by mattrossman** [sketchpunklabs/ossos#12]
I'm trying to run this project locally. I followed the setup instructions including cloning the resources repository, but I'm facing an error when running `npm run dev`:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/22670878/228934158-8b34bf67-2950-4108-9061-d536b6aaeed5.png">

Looking at [the docs](https://www.npmjs.com/package/vite-plugin-list-directory-contents) for `vite-plugin-list-directory-contents`, it seems the import statement in this project's Vite config is the issue.

The docs say:

```ts
import { directoryPlugin } from 'vite-plugin-list-directory-contents';
```

Compared to the usage here:

https://github.com/sketchpunklabs/ossos/blob/d5b1843a5ef715c99d9ffe22c08157e9046177b0/vite.config.js#L3

If I remove `/dist/plugin.js` from the import path, then I can run the `npm run dev` command successfully.

I wonder if this behavior is caused by different versions of dependencies getting installed on my end. I notice there is no lockfile being tracked in this project, perhaps that would reduce the chances of contributors facing version mismatches.

**Comment by sketchpunk** [comment]
Yea, the plugin changed. I saw the problem recently when I started rebuilding lib in the "ossos_next" branch. I fixed it in there but forgot to fix it in the main branch.
